version: '4'

services:
  bind9:
    restart: always
    image: internetsystemsconsortium/bind9:9.18
    ports:
      - 53:53/tcp
      - 53:53/udp
      - "127.0.0.1:953:953"
    volumes:
      - ./Bind9/config:/etc/bind
      - ./Bind9/working:/var/cache/bind
      - ./Bind9/zones:/var/lib/bind
      - ./Bind9/log:/var/log
