version: '4'

volumes:
  #for bind9
  config:
  working:
  zones:
  log:


services:
  bind9:
    restart: always
    image: internetsystemsconsortium/bind9:9.18
    ports:
      - 53:53/tcp
      - 53:53/udp
      - "127.0.0.1:953:953"
    volumes:
      - config:/etc/bind
      - working:/var/cache/bind
      - zones:/var/lib/bind
      - log:/var/log
