= Project goals:

. Single command deployment for both the server and clients
.. Either all necessary components will be installed on a single image or defined in a docker compose file.

== Server - VPS
. Bind9 - the whole point of this program
. a database - a place to store all the zones 
.. looking at mongo right now, but am flexible 
. a middleware to convert data in the database to a traditional text file for Bind9
.. Bind9 has a system like this, but only if you are running a blind master DNS server and a public secondary server. I have no intention of running two bind9 instances. A script to query the DB and formatting the data should not be too hard.
.. The plan is that the script will write the file with a unique file name based on the date and time. Then the script will symlink those files to the master file location that Bind9 reads. This way all the changes will be stored and if something breaks a previous version of the file can be quickly entered.
. a method to respond to queriers of "what is my public IP"
.. ICanHazIP.com is a public service offering this functionality, and I will make that an option, but I want a fully self contained option as well.
. ssh - to let the clients update the DB
. a set up wizard for fast deployment

== Client - home machines
. cron - on a timed basis the client should check its public IP 
.. if the public IP has changed it will kick off an update command. It does not need to blindly phone home and make the server check.
. an ssh cert to update the DB
.. I want to handle security with a password-less SSH cert and minimal privileges to only update the DB

== reverse proxy
. I am not sure if the reverse proxy needs to live the server or the clients, but I need to figure this out.
.. I want to open as few ports on the firewalls as possible. I think that if I put the reverse proxy on the client I will not need to open as many ports on the firewalls.